"""Protocol interfaces for perception and action layers."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from screenagent.types import Rect, UIElement


@runtime_checkable
class Perceiver(Protocol):
    def get_ui_tree(self, app_name: str) -> UIElement | None: ...
    def screenshot(self, region: Rect | None = None) -> bytes: ...
    def get_text_content(self, element_id: str) -> str: ...


@runtime_checkable
class Actor(Protocol):
    def click(self, x: float, y: float) -> None: ...
    def double_click(self, x: float, y: float) -> None: ...
    def type_text(self, text: str) -> None: ...
    def key_press(self, key: str, modifiers: list[str] | None = None) -> None: ...
    def scroll(self, x: float, y: float, dx: float, dy: float) -> None: ...


@runtime_checkable
class BrowserPerceiver(Protocol):
    async def connect(self, port: int | None = None) -> None: ...
    async def get_dom(self) -> str: ...
    async def evaluate_js(self, expression: str) -> str: ...
    async def get_page_url(self) -> str: ...


@runtime_checkable
class BrowserActor(Protocol):
    async def navigate(self, url: str) -> None: ...
    async def click_element(self, selector: str) -> None: ...
    async def type_in_element(self, selector: str, text: str) -> None: ...
